import React from 'react';
import { useApp } from '../context/AppContext';
import { X, FileText, Download, Copy, Check } from 'lucide-react';

export default function ReportModal() {
  const { selectedReport, setSelectedReport } = useApp();
  const [copied, setCopied] = React.useState(false);

  if (!selectedReport) return null;

  const generateMarkdownContent = () => {
    let md = `# ${selectedReport.title}\n`;
    md += `Date: ${selectedReport.timestamp}\n\n`;
    md += `## Executive Summary\n${selectedReport.summary}\n\n`;
    selectedReport.sections.forEach(sec => {
      md += `### ${sec.heading}\n${sec.content}\n\n`;
    });
    md += `---\nGenerated by DocuMind AI Enterprise RAG Engine\n`;
    return md;
  };

  const handleDownload = () => {
    const mdText = generateMarkdownContent();
    const blob = new Blob([mdText], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${selectedReport.title.replace(/\s+/g, '_')}.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(generateMarkdownContent());
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="fixed inset-0 z-50 bg-slate-950/80 backdrop-blur-md flex items-center justify-center p-4">
      <div className="w-full max-w-2xl bg-slate-900 border border-cyan-500/30 rounded-2xl shadow-2xl overflow-hidden glass-panel flex flex-col max-h-[85vh]">
        
        {/* Header */}
        <div className="px-6 py-4 border-b border-slate-800 flex items-center justify-between bg-cyan-950/30 shrink-0">
          <div className="flex items-center gap-2.5">
            <div className="p-2 rounded-lg bg-cyan-500/10 border border-cyan-500/20 text-cyan-400">
              <FileText className="w-5 h-5" />
            </div>
            <div>
              <h3 className="font-bold text-sm text-slate-100">
                {selectedReport.title}
              </h3>
              <p className="text-xs text-cyan-300 font-mono">
                Exported: {selectedReport.timestamp}
              </p>
            </div>
          </div>

          <button
            onClick={() => setSelectedReport(null)}
            className="p-1.5 rounded-lg text-slate-400 hover:text-slate-100 hover:bg-slate-800 transition-colors"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Scrollable Report Body */}
        <div className="p-6 overflow-y-auto space-y-5 text-slate-200 text-xs">
          
          {/* Summary Banner */}
          <div className="p-4 rounded-xl bg-slate-950 border border-slate-800 space-y-1">
            <span className="text-[10px] uppercase font-bold text-cyan-400 tracking-wider">Executive Overview</span>
            <p className="text-sm font-medium text-slate-100 leading-relaxed">
              {selectedReport.summary}
            </p>
          </div>

          {/* Sections */}
          <div className="space-y-4">
            {selectedReport.sections.map((sec, idx) => (
              <div key={idx} className="p-4 rounded-xl bg-slate-950/60 border border-slate-800 space-y-1.5">
                <h4 className="text-xs font-bold text-indigo-300 uppercase tracking-wide">
                  {sec.heading}
                </h4>
                <p className="text-xs text-slate-300 leading-relaxed">
                  {sec.content}
                </p>
              </div>
            ))}
          </div>
        </div>

        {/* Footer */}
        <div className="px-6 py-4 border-t border-slate-800 bg-slate-950/50 flex items-center justify-between shrink-0">
          <button
            onClick={handleCopy}
            className="px-4 py-2 rounded-xl bg-slate-800 hover:bg-slate-700 text-xs font-semibold text-slate-200 transition-colors flex items-center gap-2"
          >
            {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
            <span>{copied ? 'Copied' : 'Copy Markdown'}</span>
          </button>

          <button
            onClick={handleDownload}
            className="px-5 py-2 rounded-xl bg-gradient-to-r from-cyan-600 to-indigo-600 hover:from-cyan-500 hover:to-indigo-500 text-xs font-bold text-white transition-all flex items-center gap-2 shadow-lg shadow-cyan-600/20"
          >
            <Download className="w-3.5 h-3.5" />
            <span>Download Report (.md)</span>
          </button>
        </div>
      </div>
    </div>
  );
}
